# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da6ddd3399c8bf4f68bf85f430c246788fcc7dc7bd82698aa4d29df08dfd6ab53577cda59d9941b174019984ca11a8598d19f0be121bcc266160af9e2e01bb30

test:
  secret_key_base: ce2a65b480722d2711448436c38ed3fbfbc6414a0dd68dcff383779f9287379e7b5565650854ab0e8a975aefa782fabb8234b0cc4e27c147cd59dc84f999a70b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
